### ISSUE TITLE
Need a server prefix

### ISSUE THREAD

**Issue by MariusCC** [neillturner/kitchen-softlayer#3]
When having multiple suites and trying to run kitchen with --parallel we get the error bellow.
I think a server-prefix (like in kitchen-openstack driver) will fix the issue by having different names for each testing VM.

`.-----> Destroying <admin-REDHAT-7-64>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 2 actions failed.
>>>>>>     Failed to complete #destroy action: [Expected([200, 201]) <=> Actual(500 InternalServerError)
excon.error.response
  :body          => "{\"error\":\"This cancellation could not be processed please contact support.This cancellation could not be processed. Please contact support. There is currently an active transaction.\",\"code\":\"SoftLayer_Exception_Public\"}"`

**Comment by neillturner** [comment]
added this to release 0.1.0. 
I would be grateful if you could test.

**Comment by MariusCC** [comment]
still broken. bellow my kitchen.yml and the result.
looks like instead of creating 2(platforms)x4(test suites)=8VMs, kitchen is creating only 2 VMs.


---------------------------------------------------------------------------------
kitchen.yml
---------------------------------------------------------------------------------
driver:
  name: softlayer
  key_name: 'somename'
  ssh_key: <%= ENV['HOME'] %>/.ssh/id_rsa
  server_name_prefix: 'travisci_ihs'
  domain: example.com
  datacenter: somename
  destroy_wait: true
  destroy_timeout: 600
  ssh_timeout: 300
  tags: 
    - travis
    - continuousbuilds

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.17.44

verifier:
  name: inspec
  format: cli
  sudo: true

transport:
  name: ssh
  connection_timeout: 300
  keepalive: true
  keepalive_interval: 15

platforms:
  - name: REDHAT_6_64
    driver_plugin: softlayer
    driver_config:
      os_code: 'REDHAT_6_64'
      username: root
      cpu: 1
      ram: 2048
      disk: 25
      flavor_id: m1.small
      hostname: travisci-imrh6
  - name: REDHAT_7_64
    driver_plugin: softlayer
    driver_config:
      os_code: 'REDHAT_7_64'
      username: root
      cpu: 1
      ram: 2048
      disk: 25
      flavor_id: m1.small
      hostname: travisci-imrh7

suites:
  - name: admin-v85
    includes: [
      'REDHAT_6_64',
      'REDHAT_7_64'
    ]
    run_list:
      - role[somename]
  - name: nonAdmin-v85
    includes: [
      'REDHAT_6_64',
      'REDHAT_7_64'
    ]
    run_list:
      - role[somename]
  - name: admin-v90
    includes: [
      'REDHAT_6_64',
      'REDHAT_7_64'
    ]
    run_list:
      - role[somename]
  - name: nonAdmin-v90
    includes: [
      'REDHAT_6_64',
      'REDHAT_7_64'
    ]
    run_list:
      - role[somename]


---------------------------------------------------------------------------------
kitchen.log
---------------------------------------------------------------------------------
Instance                  Driver     Provisioner  Verifier  Transport  Last Action
admin-v85-REDHAT-6-64     Softlayer  ChefSolo     Inspec    Ssh        Created
admin-v85-REDHAT-7-64     Softlayer  ChefSolo     Inspec    Ssh        Created
nonAdmin-v85-REDHAT-6-64  Softlayer  ChefSolo     Inspec    Ssh        Created
nonAdmin-v85-REDHAT-7-64  Softlayer  ChefSolo     Inspec    Ssh        Created
admin-v90-REDHAT-6-64     Softlayer  ChefSolo     Inspec    Ssh        Created
admin-v90-REDHAT-7-64     Softlayer  ChefSolo     Inspec    Ssh        Created
nonAdmin-v90-REDHAT-6-64  Softlayer  ChefSolo     Inspec    Ssh        Created
nonAdmin-v90-REDHAT-7-64  Softlayer  ChefSolo     Inspec    Ssh        Created
+ kitchen exec -c 'hostname && ip a s eth1'
-----> Execute command on admin-v85-REDHAT-6-64.
       travisci-imrh6.example.com
       3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
           link/ether 06:49:56:e9:91:0f brd ff:ff:ff:ff:ff:ff
           inet xxx.xxx.124.237/29 brd xxx.xxx.124.239 scope global eth1
           inet6 fe80::449:56ff:fee9:910f/64 scope link 
       valid_lft forever preferred_lft forever
-----> Execute command on admin-v85-REDHAT-7-64.
       travisci-imrh7.example.com
       3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
           link/ether 06:b5:77:09:25:6f brd ff:ff:ff:ff:ff:ff
           inet xxx.xxx.124.236/29 brd xxx.xxx.124.239 scope global eth1
       valid_lft forever preferred_lft forever
           inet6 fe80::4b5:77ff:fe09:256f/64 scope link 
       valid_lft forever preferred_lft forever
-----> Execute command on nonAdmin-v85-REDHAT-6-64.
       travisci-imrh6.example.com
       3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
           link/ether 06:49:56:e9:91:0f brd ff:ff:ff:ff:ff:ff
           inet xxx.xxx.124.237/29 brd xxx.xxx.124.239 scope global eth1
           inet6 fe80::449:56ff:fee9:910f/64 scope link 
       valid_lft forever preferred_lft forever
-----> Execute command on nonAdmin-v85-REDHAT-7-64.
       travisci-imrh7.example.com
       3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
           link/ether 06:b5:77:09:25:6f brd ff:ff:ff:ff:ff:ff
           inet xxx.xxx.124.236/29 brd xxx.xxx.124.239 scope global eth1
       valid_lft forever preferred_lft forever
           inet6 fe80::4b5:77ff:fe09:256f/64 scope link 
       valid_lft forever preferred_lft forever
-----> Execute command on admin-v90-REDHAT-6-64.
       travisci-imrh6.example.com
       3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
           link/ether 06:49:56:e9:91:0f brd ff:ff:ff:ff:ff:ff
           inet xxx.xxx.124.237/29 brd xxx.xxx.124.239 scope global eth1
           inet6 fe80::449:56ff:fee9:910f/64 scope link 
       valid_lft forever preferred_lft forever
-----> Execute command on admin-v90-REDHAT-7-64.
       travisci-imrh7.example.com
       3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
           link/ether 06:b5:77:09:25:6f brd ff:ff:ff:ff:ff:ff
           inet xxx.xxx.124.236/29 brd xxx.xxx.124.239 scope global eth1
       valid_lft forever preferred_lft forever
           inet6 fe80::4b5:77ff:fe09:256f/64 scope link 
       valid_lft forever preferred_lft forever
-----> Execute command on nonAdmin-v90-REDHAT-6-64.
       travisci-imrh6.example.com
       3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
           link/ether 06:49:56:e9:91:0f brd ff:ff:ff:ff:ff:ff
           inet xxx.xxx.124.237/29 brd xxx.xxx.124.239 scope global eth1
           inet6 fe80::449:56ff:fee9:910f/64 scope link 
       valid_lft forever preferred_lft forever
-----> Execute command on nonAdmin-v90-REDHAT-7-64.
       travisci-imrh7.example.com
       3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
           link/ether 06:b5:77:09:25:6f brd ff:ff:ff:ff:ff:ff
           inet xxx.xxx.124.236/29 brd xxx.xxx.124.239 scope global eth1
       valid_lft forever preferred_lft forever
           inet6 fe80::4b5:77ff:fe09:256f/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by neillturner** [comment]
unfortunately i don't have access to softlayer to debug. 
I suggest you run your kitchen commands with -l debug 
and add some debug statements in the code to see what's happened. 
ruby is pretty easy to code. 
It may well be that with the server prefix it only creates two VMs one for each prefix and 
runs 4 test suites one after another.   
I don't see the the kitchen command you are running i assume you are doing something like 
 kitchen test --parallel
i think the parallel support is in the core test kitchen code rather than the plugin code.

**Comment by MariusCC** [comment]
sorry, I forgot to put the commands I've run (see bellow). no parallel. 
so, yep, will debug and fix the driver myself. just hopped to avoid going through the IBM legal process for publishing code.

      kitchen destroy -l debug > /dev/null 2>&1
      kitchen create -l debug
      kitchen list
      kitchen exec  -c 'hostname && ip a s eth1'

**Comment by neillturner** [comment]
If you are not running with parallel then running 'kitchen test'  runs sequentially creating a VM, converging, verifying and then destroying for each of the environments. 

generally you do a kitchen list to see all the environments before you run them.  

if i can see the  log file with -l debug from the kitchen create then i could see what is happening. you can always email it to my privately if you don't want to put on internet and edit out any internal info you don't want shared.
